spring:
  application:
    name: usuarios
  profiles:
    active: dev

# Configuración de Swagger / OpenAPI traducida
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs