server:
  port: ${PORT:8085} # Railway le asignará un puerto dinámico

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never # En la nube no queremos que ande ejecutando scripts iniciales en cada reinicio

  jpa:
    defer-datasource-initialization: false
    show-sql: false # Apagamos los logs pesados en producción
    hibernate:
      ddl-auto: validate # Valida la BD 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect